/**
 * e-幹事 API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface MeetingResponse {
    meetingId?: string;

    name?: string;

    startAt?: Date;

    endAt?: Date;

    organizers?: Array<models.OrganizerResponse>;

    invitees?: Array<models.InviteeResponse>;

    attendees?: Array<models.AttendeeResponse>;

    sponsers?: Array<models.SponsorResponse>;

}
